package midi;

/**
 * Created by mrzl on 16.01.2015.
 */
public enum VisualParameterEnum {
    MARE_UNDARUM_1, MARE_UNDARUM_2, MARE_UNDARUM_3,
    AXIS_MUNDI_1, AXIS_MUNDI_2, AXIS_MUNDI_3, AXIS_MUNDI_4,
    AURORA_1, AURORA_2, AURORA_3, AURORA_4, AURORA_5, AURORA_6,

    UPDATE_DELAY,
    MIN_HUE,
    MAX_HUE,
    BACKGROUND_OPACITY,

    M,
    N,
    JUMPYNESS,
    PARTICLE_SIZE,
    PARTICLE_COUNT,
    PARTICLE_OPACITY,
    POLES,
    SCALE,
    INTENSITY,
    THRESHOLD,
    BLOOM_SIZE,
    BLOOM_SIGMA,

    CONTRAST,
    BRIGHTNESS,

    BLUR_DIRECTION,
    BLUR_STRENGTH,
    CUTOFF
}
