package osc;

/**
 * Created by mrzl on 06.01.2015.
 */
public enum SoundInputParameterEnum {
    ATTACK_PARAMETER1, ATTACK_PARAMETER2, ATTACK_PARAMETER3,
    FREQUENCY_PARAMETER1, FREQUENCY_PARAMETER2, FREQUENCY_PARAMETER3,
    AMPLITUDE_PARAMETER1, AMPLITUDE_PARAMETER2, AMPLITUDE_PARAMETER3,
    PEAK_PARAMETER1, PEAK_PARAMETER2, PEAK_PARAMETER3,
    FUNDAMENTAL_PARAMETER1, FUNDAMENTAL_PARAMETER2, FUNDAMENTAL_PARAMETER3,
    NEWNOTE_PARAMETER1, NEWNOTE_PARAMETER2, NEWNOTE_PARAMETER3
}
