package osc;

/**
 * Created by mrzl on 06.01.2015.
 */
public enum SoundInputParameterEnum {
    ATTACK_PARAMETER1, ATTACK_PARAMETER2, ATTACK_PARAMETER3,
    FREQUENCY_PARAMETER1, FREQUENCY_PARAMETER2, FREQUENCY_PARAMETER3,
    AMPLITUDE_PARAMETER1, AMPLITUDE_PARAMETER2, AMPLITUDE_PARAMETER3
}
